name: tflite_flutter_processing
description: Easy, fast processing and manipulation input and output of TensorFlow Lite Models.
version: 0.4.1
homepage: https://www.github.com/lucasoskorep/tflite_flutter_processing

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  quiver: ^3.0.1
  path_provider: ^2.0.1
  tflite_flutter: ^0.10.4
  tuple: ^2.0.0
  camera: ^0.10.0
  ffi: ^2.0.1
  image: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: io.chaosdev.tflite_flutter_processing
        pluginClass: TfliteFlutterProcessingPlugin
      ios:
        pluginClass: TfliteFlutterProcessingPlugin
      linux:
        pluginClass: TfliteFlutterProcessingPlugin
      macos:
        pluginClass: TfliteFlutterProcessingPlugin
      windows:
        pluginClass: TfliteFlutterProcessingPlugin